### ISSUE TITLE
Add global profile to check Javadoc

### ISSUE THREAD

**Issue by bourretp** [roboconf/roboconf-parent#4]
During the last Roboconf platform release, we ran into a problem because:
- The build was done using (Oracle's) Java 8 (with class targeting java 7)
- Javadoc 8 has never been run for the platform project.
- The Javadoc 8 is, by default, very strict with the javadoc format... too strict in fact!
- The release process triggered maven-javadoc-plugin, which has miserably failed, leaving the release in an intermediate state (release commits pushed, tags created, but no artifact deployed on the sonatype repo)

In order to avoid this (and keeping to possibility to use java 8), we need to run periodically (Travis?) a job that generates the javadoc for the whole project. While the default javadoc 8 configuration is really restrictive, we can use a subset, e.g. `-Xdoclint:reference,html,syntax`.

We could include a profile in the global project's parent pom, and activate the profile `javadoc-deep-checks` with the Java8 build of Travis. Activation would require both:
- `<jdk>[1.8,)</jdk>` AND
- `<property><name>roboconf.javadoc.check</name><value>true</value></property>`

Profile & activation property name are subject to change.

**Comment by bourretp** [comment]
_Correction_: maybe we need 2 profiles.
- A regular one which disables excessive doclint checks when we use java 8
- Another one that share the same configuration, but force the javadoc:javadoc goal. This one is for Travis

WDYT?

**Comment by vincent-zurczak** [comment]
Maybe we could be change the meaning of **roboconf.javadoc.check**.
Instead of being a boolean, it could be the linter's parameters.

`-Xdoclint:none` by default.
And `-Xdoclint:reference,html,syntax` in Travis builds.
1. This way, we have a single profile.
2. We can update the linter's parameters without releasing a new parent.

And we will document it on the web site.

**Comment by bourretp** [comment]
[MJAVADOC-368](https://issues.apache.org/jira/browse/MJAVADOC-368) prevents the use of commas in the value of configuration properties (params w/ commas are handled as arrays).

Until this issue get fixed, I suggest to use a _fixed Xdoclint configuration_ (namely `-Xdoclint:reference -Xdoclint:html -Xdoclint:syntax`, without a comma) in a profile. Switching to arg-provided value, as soon as MJAVADOC-368 gets fixed will be trivial.

OK with that?

**Comment by vincent-zurczak** [comment]
OK for me.
